### ISSUE TITLE
BTC增加隔离见证支持

### ISSUE THREAD

**Issue by sunxiansong** [dabankio/wallet-core#14]
**提示**：测试中如果使用bitcoind 作为后端，请增加参数 `-addresstype=legacy` ,否则默认生成的地址是`p2sh-segwit`类型，要注意这点

---

### 需求

BTC增加对隔离见证地址对签名支持，目前btcd中的签名不支持隔离见证，这个有待商榷

如果增加隔离见证支持，也要考虑如何获得p2wsh下的解锁脚本，在测试中发现，bitcoin-core如果不导入私钥的话获取的utxo不包含redeemScript（另外bitcoin-core rpc getAddressInfo 也可以取得地址对应的redeemScript，不过不确定是否要导入私钥）, 这个应该可以离线计算得到，有待研究

**Comment by erzaxs** [comment]
done  #37
