### ISSUE TITLE
eth 多签方式的疑问

### ISSUE THREAD

**Issue by 0xJayShen** [dabankio/wallet-core#20]
现在比如2-3 的合约,两次合约拥有者签名,最后还要再由一个人签名上链,也就是三次,是这样吗?能要一下开发者的联系方式吗

**Comment by erzaxs** [comment]
hallo, 实际上ETH的多签取决于合约的实现，可以参考具体的合约代码：https://github.com/dabankio/wallet-core/blob/dev/core/eth/internal/contracts/SimpleMultiSig.sol

目前的这个实现，需要收集成员签名后上链，具体来说有2种签名
1. 对转账数据进行签名，本质上是拼接参数后用椭圆曲线算法进行签名，签名好的数据用于构造调用合约的参数 ，合约被调用时合约内部校验签名（参考： https://github.com/dabankio/wallet-core/blob/b4f5db0540dbe2d771a8054124d5f0bd35e3f827/core/eth/internal/simplemultisig.go#L151）
2. 对上链交易进行签名，即一般的ETH transaction sign

可以通过 sunxiansong#dabank.io  (mail)联系到我，如果需要其他联系方式可以在邮件里说明
